trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_Backend
    displayName: 'Build Spring Boot Backend'
    jobs:
      - job: BuildBackend
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitecture: 'x64'

          - script: |
              cd OrienGo-Backend
              ./mvnw clean install
            displayName: 'Build Backend with Maven'

  - stage: Build_Frontend
    displayName: 'Build Angular Frontend'
    jobs:
      - job: BuildFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd OrienGo-Frontend
              npm install
              npm run build
            displayName: 'Build Angular App'
