export enum CoachSpecialization {
  CAREER_COUNSELING = "CAREER_COUNSELING",
  ACADEMIC_GUIDANCE = "ACADEMIC_GUIDANCE",
  STUDY_ABROAD = "STUDY_ABROAD",
  SCHOLARSHIP_PREPARATION = "SCHOLARSHIP_PREPARATION",
  EXAM_PREPARATION = "EXAM_PREPARATION",
  INTERNSHIP_PREPARATION = "INTERNSHIP_PREPARATION",
  JOB_SEARCH = "JOB_SEARCH",
  INTERVIEW_PREPARATION = "INTERVIEW_PREPARATION",
  CV_RESUME_BUILDING = "CV_RESUME_BUILDING",
  PERSONAL_DEVELOPMENT = "PERSONAL_DEVELOPMENT",
  GOAL_SETTING = "GOAL_SETTING",
  SKILL_DEVELOPMENT = "SKILL_DEVELOPMENT",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
  LIFE_COACHING = "LIFE_COACHING"
}
