export enum EducationLevel {
  MIDDLE_SCHOOL = 'MIDDLE_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  POST_SECONDARY = 'POST_SECONDARY',
  UNIVERSITY = 'UNIVERSITY',
  GRADUATE = 'GRADUATE',
  OTHER = 'OTHER'
}