-- -- Liaison des formations aux emplois existants
-- -- V1_10__link_trainings_to_jobs.sql
--
-- -- Liens pour le Développeur Full-Stack (ID: 1)
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (1, 1),  -- Licence Informatique
--                                                          (1, 6),  -- Formation Développeur Web Full-Stack
--                                                          (1, 11), -- Bootcamp Développement React
--                                                          (1, 21), -- Cours Machine Learning - Coursera
--                                                          (1, 26), -- Stage Développeur Frontend
--                                                          (1, 31), -- Apprentissage Développeur Full-Stack
--                                                          (1, 36), -- Atelier Introduction à React
--                                                          (1, 46); -- Auto-formation Développement Web
--
-- -- Liens pour le Psychologue Clinicien (ID: 2)
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (2, 2),  -- Master en Psychologie Clinique
--                                                          (2, 7),  -- Formation Conseiller en Orientation
--                                                          (2, 23), -- Cours Psychologie Positive - edX
--                                                          (2, 42), -- Séminaire Psychologie Positive
--                                                          (2, 47); -- Auto-formation Data Science (pour la recherche)
--
-- -- Liens pour le Chef de Projet Marketing (ID: 3)
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (3, 4),  -- Licence en Marketing Digital
--                                                          (3, 8),  -- Formation Chef de Projet IT
--                                                          (3, 15), -- Bootcamp Marketing Digital
--                                                          (3, 18), -- Certification Scrum Master
--                                                          (3, 24), -- Formation SEO Avancé - LinkedIn Learning
--                                                          (3, 29), -- Stage Marketing Digital
--                                                          (3, 35), -- Apprentissage Chef de Projet
--                                                          (3, 39), -- Atelier Gestion de Projet Agile
--                                                          (3, 44), -- Séminaire Marketing Automation
--                                                          (3, 49); -- Auto-formation Marketing Digital
--
-- -- Liens pour le Designer UX/UI (ID: 4)
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (4, 5),  -- Master en Design UX/UI
--                                                          (4, 14), -- Bootcamp UX Design
--                                                          (4, 25), -- Cours Design Thinking - MIT OpenCourseWare
--                                                          (4, 28), -- Stage UX Researcher
--                                                          (4, 33), -- Apprentissage UX Designer
--                                                          (4, 37), -- Atelier Design Sprint
--                                                          (4, 43), -- Séminaire Transformation Digitale
--                                                          (4, 48); -- Auto-formation Design UX
--
-- -- Liens pour l'Ingénieur Data Scientist (ID: 5)
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (5, 3),  -- École d'Ingénieur en Data Science
--                                                          (5, 9),  -- Formation Analyste de Données
--                                                          (5, 12), -- Bootcamp Python Data Science
--                                                          (5, 16), -- Certification AWS Solutions Architect
--                                                          (5, 21), -- Cours Machine Learning - Coursera
--                                                          (5, 27), -- Stage Data Analyst
--                                                          (5, 32), -- Apprentissage Data Scientist
--                                                          (5, 40), -- Atelier Analyse de Données
--                                                          (5, 41), -- Séminaire IA et Futur du Travail
--                                                          (5, 47); -- Auto-formation Data Science
--
-- -- Formation en Cybersécurité pour les profils TECH
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (1, 45), -- Séminaire Cybersécurité (pour Développeur Full-Stack)
--                                                          (5, 45); -- Séminaire Cybersécurité (pour Data Scientist)
--
-- -- Formation en Communication pour les profils SOCIAUX
-- INSERT INTO job_training_links (job_id, training_id) VALUES
--                                                          (2, 10), -- Formation Community Manager (pour Psychologue)
--                                          (3, 10); -- Formation Community Manager (pour Marketing)
--
-- -- Note: Les formations en Innovation et Leadership sont déjà incluses dans les sections principales ci-dessus
