#FROM eclipse-temurin:21-jdk
#WORKDIR /app
#COPY target/OrienGO.jar OrienGO.jar
#COPY wait-for-it.sh wait-for-it.sh
#
#RUN chmod +x wait-for-it.sh
#ENV SPRING_PROFILES_ACTIVE=docker
#
#EXPOSE 8877
#ENTRYPOINT ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "OrienGO.jar"]