# a top-level
version: '3.8'

# a top-level
services:
  postgres:

    image: postgres

    container_name: oriengo_postgres
    environment:
      POSTGRES_USER: postgres #default
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: oriengo_db #default is postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - oriengo-net

  oriengo-app:

    build:
      context: .
      dockerfile: Dockerfile #build: .

    container_name: oriengo_app
    ports:
      - "8877:8877"
    depends_on:
      - postgres #the service not the image
    networks:
      - oriengo-net
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"   # Web UI
      - "1025:1025"   # SMTP server

# add a top-level for clarity
volumes:
  pgdata:

networks:
  oriengo-net:
