server:
  port: 8888

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: ""
    driver-class-name: ""
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

logging:
  level:
    org.springframework: INFO
