server:
  port: 8877
spring:
  application:
    name: OrienGo
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/oriengo_db
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
