server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/oriengo_db
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
media:
  upload-dir: uploads/
