spring:
  application:
    name: OrienG0
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
#  flyway:
#    enabled: true
#    postgresql:
#      transactional-lock: false
#    baseline-on-migrate: true
#    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update # FlyWay: none
    show-sql: true
    open-in-view: false  # Add this line
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    check-template-location: false
logging:
  level:
    org.springframework.jdbc: DEBUG